### ISSUE TITLE
Promo materials from Stickermule

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#75] opened 2018-05-01 13:08 UTC
Let's ask from Stickermule promo materials - more creative ones like magnets, stickers etc. Let's brainstorm here about the materials we need.

Deadline to start the process: 4.05.2018
Deadline to receive the stickers: 30.05.2018

**Comment by elioqoshi** [comment] 2018-05-31 14:45
A duplicate of this has been opened:
https://github.com/uracreative/task-management/issues/81

Closing this here since discussion has started in 81

**Closed as completed by elioqoshi** 2018-05-31 14:45 UTC
Labels: Internal: Outreach, Priority: Medium, Internal: Identihub
