### ISSUE TITLE
Identihub website: localization

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#38] opened 2018-01-10 15:23 UTC
We need to give the opportunity to Identihub contributors to help with the localization of the website. The platform should integrate with Github for better contributions and documentation. @marianaballa please collaborate with @Borisbudini and introduce Weblate as a potential platform that can be used.
@AnXh3L0 please explore the best way of switching between the languages in the website. 

Deadline (going live): week 29.01.2018

**Comment by kominoshja** [comment] 2018-02-12 15:17
The deadline is too early.
@marianaballa @AnXh3L0 can we start working on this?

**Comment by elioqoshi** [comment] 2018-02-18 17:10
Let's hold on this for the moment. @rskikuli we need to coordinate on this before ideally. 

@Borisbudini this shouldn't be Anxhelo's responsibility, he has enough on his hands now.

**Comment by rskikuli** [comment] 2018-04-11 15:46
@Borisbudini please propose a new deadline that you think it is realistic. Thank you.

**Comment by elioqoshi** [comment] 2018-04-11 17:01
Considering this is related to frontend, assigning Anxhelo as well.

@AnXh3L0 do you think we can have the Albanian Identihub landing page integrated with Weblate ready for the Work Week?

**Comment by AnXh3L0** [comment] 2018-04-11 17:53
Yes, we will start deploying a test website and link it with Weblate for localization.

**Comment by rskikuli** [comment] 2018-06-04 08:36
This is long overdue. Please @AnXh3L0 pleae assign a new deadline. Thank you.

**Comment by AnXh3L0** [comment] 2018-06-04 14:48
There has been some problems with the deployment of the new website and I can't find out why because the build is successful on my machine and no error occurs. Will investigate the issue further on.

**Comment by rskikuli** [comment] 2018-06-04 16:33
Sure. Just share an idea of the time needed for the implementation.

**Comment by AnXh3L0** [comment] 2018-06-04 16:36
If we manage to solve the deployment, everything can be ready in less than 1 hour because the website and translations are already linked.

**Comment by elioqoshi** [comment] 2018-06-16 17:21
@Borisbudini we need to wrap this up asap please. Let's not drop the ball on this.

**Comment by rskikuli** [comment] 2018-06-26 10:38
Ping @Borisbudini .

**Comment by kominoshja** [comment] 2018-06-26 10:39
There's nothing that can be done from my side. Weblate is ready, the site is ready. We need a parser as @AnXh3L0 said, but I lack the skills to do that

**Comment by rskikuli** [comment] 2018-06-26 11:03
Please an update @AnXh3L0 .

**Comment by AnXh3L0** [comment] 2018-07-05 10:00
For the moment @rskikuli we will need to create a parser because Weblate doesn't produce the type of file we want; this might take a while because it is not a priority at the moment and as we don't have many contributors that translate, we can delete that one line of code manually, which would still be needed when we add the new languages in the website.

I suggest we close this as the main point of the issue is solved, the page is localizable and it works.

**Comment by elioqoshi** [comment] 2018-07-05 10:08
@AnXh3L0 @Borisbudini I'd suggest being clear with the status as it was not unless someone followed the chats on Mattermost. 

@rskikuli so in a nutshell: Localization works and Weblate pushes translations automatically to the Identihub landing page automatically. This generated file has however some formatting problems and doesn't work right away on default, so anyone who merges the changes needs to do a few tweaks to it. This is fine as we do languages ourselves but we need to automate this process in the future when we will actually have more contributors.

**Comment by elioqoshi** [comment] 2018-07-07 15:43
Closing as it works as Anxhelo described. If we want to automate the parsing add and specific other languages we can open other issues

**Closed as completed** 2018-07-07 15:43 UTC
Labels: Priority: High, Internal: Identihub, Internal: Overdue

**Comment by kominoshja** [comment] 2018-07-10 00:32
P.S: I automated the process by using a [parser](https://github.com/uracreative/identihub.co/blob/master/_i18n/parser.sh).  All we need to do is add the language code and flag to _config.yml before merging PRs
